sudo: required
dist: bionic

language: c
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y krb5-config libevent-dev libkrb5-dev libmodule-build-perl libpcre3-dev libtest-pod-perl libtest-minimumversion-perl libtest-pod-coverage-perl libtest-strict-perl libtest-synopsis-perl perl php5-cli pkg-config python-all-dev ruby-all-dev
env: AUTHOR_TESTING=1
script: ./bootstrap && ./configure --enable-perl --enable-php --enable-python --enable-ruby && make warnings && make check

branches:
  except:
    - /^debian\/.*/
    - java
    - pristine-tar
    - /^ubuntu\/.*/
    - /^upstream\/.*/
