# Configuration for Travis-CI continuous integration.
#
# Copyright 2016, 2018-2019 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

sudo: required
dist: bionic

language: c
compiler:
  - gcc
  - clang

before_install: sudo ci/install

script: ci/test

branches:
  except:
    - /^debian\/.*/
    - java
    - pristine-tar
    - /^ubuntu\/.*/
    - /^upstream\/.*/
